<div class="bg-white border-10 shadow w-500">
    <form action="" method="POST">
        <div class="flexed-card">
            <h1 class="center mb-20">Log in</h1>

            <!-- Error Block -->
            <?php if(isset($_SESSION['error'])){ ?>
                <div class="text-red border border-red bg-red p-10 border-10 text-center">
                    <?php 
                        echo $_SESSION['error'] ?? '';
                        unset($_SESSION['error']);
                    ?>
                </div>
            <?php };?>

            <!-- Username -->
            <label for="username" class="mt-20 ml-18 medium sm-text">Username</label>
            <input type="text" name="username" placeholder="Username" class="input mb-20" value="<?php echo $_POST['username'] ?? '' ?>">
            
            <!-- Password -->
            <label for="password" class="ml-18 medium sm-text">Password</label>
            <div class="relative">
                <input type="password" name="password" placeholder="Password" autocomplete="off" class="input fill mb-20">
                <span onclick="passwordShow()" class="absolute eye-icon">
                    <svg xmlns="http://www.w3.org/2000/svg" id="show-pass" class="h-25 w-25 pointer" fill="none" viewBox="0 0 24 24" stroke="rgb(109, 109, 109)" stroke-width="1.4">
                            <path strokeLinecap="round" strokeLinejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                            <path strokeLinecap="round" strokeLinejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
                    </svg>
                    <svg xmlns="http://www.w3.org/2000/svg" id="hide-pass" class="h-25 w-25 pointer hidden" fill="none" viewBox="0 0 24 24" stroke="rgb(109, 109, 109)" stroke-width="1.4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M13.875 18.825A10.05 10.05 0 0112 19c-4.478 0-8.268-2.943-9.543-7a9.97 9.97 0 011.563-3.029m5.858.908a3 3 0 114.243 4.243M9.878 9.878l4.242 4.242M9.88 9.88l-3.29-3.29m7.532 7.532l3.29 3.29M3 3l3.59 3.59m0 0A9.953 9.953 0 0112 5c4.478 0 8.268 2.943 9.543 7a10.025 10.025 0 01-4.132 5.411m0 0L21 21" />
                    </svg>
                </span>
            </div>

            <span class="poppins-regular md-text text-right mb-20">
                Don't have an account yet? <a href="<?php echo WEB_ROOT . '/register'; ?>">Register now!</a>
            </span>

            <button type="submit" class="btn">Submit</button>
        </div>
    </form>
</div>